allowBuilds:
  '@embedded-postgres/windows-x64': true
  esbuild: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@payloadcms/db-postgres@3.89.0'
  - '@payloadcms/drizzle@3.89.0'
  - '@payloadcms/email-resend@3.89.0'
  - '@payloadcms/graphql@3.89.0'
  - '@payloadcms/next@3.89.0'
  - '@payloadcms/plugin-cloud-storage@3.89.0'
  - '@payloadcms/plugin-seo@3.89.0'
  - '@payloadcms/richtext-lexical@3.89.0'
  - '@payloadcms/storage-vercel-blob@3.89.0'
  - '@payloadcms/translations@3.89.0'
  - '@payloadcms/ui@3.89.0'
  - payload@3.89.0
